server:
  servlet:
    encoding:
      charset: utf-8
      force: true
#cloud:
#  aws:
#    region:
#      static: ap-northeast-2
#      auto: false
#    s3:
#      bucket: sideairbnb
#    credentials:
#      access-key: AKIAQQ5QPUSNSEQEQN6V
#      secret-key: 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
#    stack:
#      auto: false
spring:
  datasource:
    url: jdbc:mysql://ls-1692012060d918e6f1e798358c98026076d919c1.c9w0jf95oc7r.ap-northeast-2.rds.amazonaws.com:3306/cream-soda?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbmasteruser
    password: ghgus531
  output:
    ansi:
      enabled: always
#    servlet:
#      multipart:
#        max-file-size: 10MB
#        max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
